remote_theme: pages-themes/cayman@v0.2.0
title: "The Influence of Diversity on Role Dynamics and Film Performance"
description: A template website for ADA
show_downloads: False
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
