#remote_theme: pages-themes/cayman@v0.2.0
#title: "The Influence of Diversity on Role Dynamics and Film Performance"
#description: A template website for ADA
#show_downloads: False
#navigation:
#  - title: Home
#    url: /
#  - title: Example
#    url: example

theme: jekyll-theme-slate
title: "aka"
#cover-img: "data/popefrancis.png"

#cover_image: url("../data/popefrancis.jpg")
#header_text_color: "rbga(255, 255, 255, 1.0)"
site_header_text_color: "rgba(105, 81, 62, 0.8)"
site_header_border_color: "rgba(105, 81, 62, 0.5)"
