theme: jekyll-theme-cayman
title: "The Influence k of Diversity on Role Dynamics and Film Performance"
description: A template website for ADA
show_downloads: False
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
