remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "The Influence k of Diversity on Role Dynamics and Film Performance"
description: A template website for ADA
show_downloads: False
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
