theme: jekyll-theme-minimal
title: "The impact of casting diversity on a film's role dynamics and performance"
description: A template website for ADA
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
